DROP DATABASE IF EXISTS database_pizza;
CREATE DATABASE database_pizza;
USE database_pizza;

CREATE TABLE IF NOT EXISTS clients (
id INT AUTO_INCREMENT NOT NULL,
nom VARCHAR(255) NOT NULL,
numero_telephone VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS sauces (
id INT AUTO_INCREMENT NOT NULL,
nom VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS croutes (
id INT AUTO_INCREMENT NOT NULL,
nom VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pizzas (
id INT AUTO_INCREMENT NOT NULL,
sauce_id INT NOT NULL,
croute_id int NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS commandes (
id INT AUTO_INCREMENT NOT NULL,
client_id INT NOT NULL,
pizza_id INT NOT NULL,
adresse VARCHAR(255) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (client_id) REFERENCES clients(id),
FOREIGN KEY (pizza_id) REFERENCES pizzas(id)
);

CREATE TABLE IF NOT EXISTS garnitures (
id INT AUTO_INCREMENT NOT NULL,
nom VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS garnitures_pizzas (
pizza_id INT NOT NULL,
garnitures_id INT NOT NULL,
FOREIGN KEY (pizza_id) REFERENCES pizzas(id),
FOREIGN KEY (garnitures_id) REFERENCES garnitures(id)
);